services:
  - type: web
    env: node
    name: pharmali-prod-backend1
    repo: https://github.com/IrhaAli/PharmAli
    buildFilter:
      paths:
        - server/**
    buildCommand: yarn && yarn build --filter=backend
    startCommand: cd server; yarn start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pharmali-prod-db1
          property: connectionString

  - type: web
    env: static
    name: pharmali-prod-frontend1
    repo: https://github.com/IrhaAli/PharmAli
    buildFilter:
      paths:
        - client/**
    buildCommand: yarn && yarn build --filter=frontend
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_GRAPHQL_HOST
        fromService:
          name: pharmali-prod-backend1
          type: web
          property: host

databases:
  - name: pharmali-prod-db1