services:
  - type: web
    env: node
    name: pharmali-prod-backend
    repo: https://github.com/IrhaAli/PharmAli.git
    buildCommand: yarn && yarn build --filter=server
    startCommand: cd server; yarn start
    enVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pharmali-prod-db
          property: connectionString

  - type: web
    env: static
    name: pharmali-prod-frontend

databases:
  - name: pharmali-prod-db